import React, { useEffect, useState } from 'react';
import { fetchIncidentById, analyzeIncidentWithGemini, updateIncidentStatus, resolveIncident } from '../services/api';
import SeverityBadge from '../components/SeverityBadge';
import StatusBadge from '../components/StatusBadge';
import { ArrowLeft, Sparkles, CheckCircle2, Check } from 'lucide-react';

export default function IncidentDetailPage({ incidentId, onBack }) {
  const [incident, setIncident] = useState(null);
  const [loading, setLoading] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [customAction, setCustomAction] = useState('');
  const [message, setMessage] = useState(null);

  const loadIncident = async () => {
    try {
      setLoading(true);
      const data = await fetchIncidentById(incidentId);
      setIncident(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (incidentId) loadIncident();
  }, [incidentId]);

  const handleAnalyzeWithGemini = async () => {
    try {
      setAnalyzing(true);
      setMessage(null);
      const updated = await analyzeIncidentWithGemini(incidentId);
      setIncident((prev) => ({ ...prev, ...updated }));
      
      if (updated.ai_source === 'gemini') {
        setMessage({ type: 'success', text: 'Google Gemini AI Analysis completed successfully!' });
      } else {
        setMessage({ type: 'warning', text: 'Gemini unavailable — generated local analysis fallback.' });
      }
    } catch (err) {
      console.error(err);
      setMessage({ type: 'error', text: 'AI Analysis request failed. Showing default local analysis.' });
    } finally {
      setAnalyzing(false);
    }
  };

  const handleStatusChange = async (newStatus) => {
    try {
      setActionLoading(true);
      const updated = await updateIncidentStatus(incidentId, newStatus);
      setIncident((prev) => ({ ...prev, ...updated }));
      setMessage({ type: 'success', text: `Incident status updated to '${newStatus}'.` });
    } catch (err) {
      console.error(err);
    } finally {
      setActionLoading(false);
    }
  };

  const handleSimulateResolution = async () => {
    try {
      setActionLoading(true);
      const res = await resolveIncident(incidentId, customAction || null);
      await loadIncident();
      setMessage({ type: 'success', text: `Simulated resolution executed: "${res.resolution.action}"` });
      setCustomAction('');
    } catch (err) {
      console.error(err);
    } finally {
      setActionLoading(false);
    }
  };

  if (loading) return <div className="page-body">Loading incident details...</div>;
  if (!incident) return <div className="page-body">Incident not found.</div>;

  const renderAiStatusBadge = () => {
    if (!incident.ai_summary) return null;
    if (incident.ai_source === 'gemini') {
      return (
        <span className="badge badge-low" style={{ fontSize: '11px' }}>
          Generated by Google Gemini
        </span>
      );
    } else {
      return (
        <span className="badge badge-medium" style={{ fontSize: '11px' }}>
          Gemini unavailable — using local analysis
        </span>
      );
    }
  };

  return (
    <div className="page-body">
      {/* Back button & Title header */}
      <div style={{ marginBottom: '20px' }}>
        <button className="btn btn-secondary" onClick={onBack} style={{ marginBottom: '12px' }}>
          <ArrowLeft size={16} /> Back to Incidents
        </button>

        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
              <span style={{ fontSize: '14px', color: 'var(--text-muted)' }}>Incident #{incident.id}</span>
              <SeverityBadge severity={incident.severity} />
              <StatusBadge status={incident.status} />
              <span className="badge" style={{ backgroundColor: 'var(--surface-hover)', color: 'var(--text-main)' }}>
                {incident.incident_type}
              </span>
            </div>
            <h2 style={{ fontSize: '24px', fontWeight: '700' }}>{incident.title}</h2>
          </div>

          {/* Action Buttons */}
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <button
              className="btn btn-primary"
              onClick={handleAnalyzeWithGemini}
              disabled={analyzing}
            >
              <Sparkles size={16} />
              {analyzing ? 'Analyzing with Gemini...' : 'Analyze with Gemini'}
            </button>

            {incident.status === 'Open' && (
              <button
                className="btn btn-warning"
                onClick={() => handleStatusChange('Investigating')}
                disabled={actionLoading}
              >
                Mark Investigating
              </button>
            )}

            {incident.status !== 'Resolved' && (
              <button
                className="btn btn-success"
                onClick={handleSimulateResolution}
                disabled={actionLoading}
              >
                <CheckCircle2 size={16} />
                Simulate Resolution
              </button>
            )}

            {incident.status !== 'Resolved' && (
              <button
                className="btn btn-secondary"
                onClick={() => handleStatusChange('Resolved')}
                disabled={actionLoading}
              >
                <Check size={16} />
                Mark Resolved
              </button>
            )}
          </div>
        </div>
      </div>

      {message && (
        <div
          className="status-banner"
          style={{
            marginBottom: '20px',
            backgroundColor: message.type === 'error' ? '#fef2f2' : message.type === 'warning' ? '#fefce8' : '#f0fdf4',
            color: message.type === 'error' ? '#991b1b' : message.type === 'warning' ? '#854d0e' : '#166534',
            border: `1px solid ${message.type === 'error' ? '#fecaca' : message.type === 'warning' ? '#fef08a' : '#bbf7d0'}`
          }}
        >
          {message.text}
        </div>
      )}

      {/* Grid Layout for Incident Overview & AI Analysis */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: '20px', marginBottom: '24px' }}>
        
        {/* Incident Summary Card */}
        <div className="panel">
          <div className="panel-header">
            <h3 className="panel-title">Incident Specifications</h3>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px', marginBottom: '16px' }}>
            <div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Type</div>
              <div style={{ fontWeight: 600 }}>{incident.incident_type}</div>
            </div>
            <div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Confidence Score</div>
              <div style={{ fontWeight: 600 }}>{(incident.confidence * 100).toFixed(0)}%</div>
            </div>
            <div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Created At</div>
              <div style={{ fontSize: '13px' }}>{incident.created_at ? new Date(incident.created_at).toLocaleString() : 'N/A'}</div>
            </div>
            <div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Resolved At</div>
              <div style={{ fontSize: '13px' }}>{incident.resolved_at ? new Date(incident.resolved_at).toLocaleString() : 'Unresolved'}</div>
            </div>
          </div>

          <div style={{ borderTop: '1px solid var(--border-color)', paddingTop: '16px' }}>
            <h4 style={{ fontSize: '14px', fontWeight: '600', marginBottom: '8px' }}>Explainable Root Cause Engine</h4>
            <div style={{ fontSize: '13px', backgroundColor: 'var(--bg-color)', padding: '12px', borderRadius: '6px', whiteSpace: 'pre-wrap' }}>
              {incident.root_cause || 'No root cause detected yet.'}
            </div>
          </div>
        </div>

        {/* Google Gemini AI Analysis Panel */}
        <div className="panel" style={{ borderLeft: '4px solid var(--primary-color)' }}>
          <div className="panel-header">
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Sparkles size={18} style={{ color: 'var(--primary-color)' }} />
              <h3 className="panel-title">Google Gemini AI Analysis</h3>
            </div>
            {renderAiStatusBadge()}
            {!incident.ai_summary && (
              <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>Click 'Analyze with Gemini' to generate</span>
            )}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            <div>
              <h4 style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '4px' }}>AI Incident Summary</h4>
              <p style={{ fontSize: '14px', fontWeight: '500' }}>
                {incident.ai_summary || 'No AI summary generated yet.'}
              </p>
            </div>

            <div>
              <h4 style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '4px' }}>Technical Explanation</h4>
              <p style={{ fontSize: '13px', color: 'var(--text-main)', lineHeight: '1.6' }}>
                {incident.ai_explanation || 'No technical explanation generated yet.'}
              </p>
            </div>

            <div>
              <h4 style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '4px' }}>Recommended Remediation</h4>
              <div style={{ fontSize: '13px', padding: '10px 12px', backgroundColor: 'var(--primary-light)', color: 'var(--primary-color)', borderRadius: '6px', fontWeight: '500' }}>
                {incident.remediation || 'No remediation recommendation generated.'}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Simulated Resolution Action Trigger */}
      {incident.status !== 'Resolved' && (
        <div className="panel" style={{ backgroundColor: 'var(--bg-color)' }}>
          <h3 className="panel-title" style={{ marginBottom: '12px' }}>Automated Safe Remediation Action</h3>
          <p style={{ fontSize: '13px', color: 'var(--text-muted)', marginBottom: '12px' }}>
            Trigger safe simulated remediation for this {incident.incident_type} incident. No real shell commands will be executed.
          </p>
          <div style={{ display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' }}>
            <input
              type="text"
              className="input-text"
              style={{ flex: 1, minWidth: '280px' }}
              placeholder={`Default: ${incident.remediation || 'Simulated service restart'}`}
              value={customAction}
              onChange={(e) => setCustomAction(e.target.value)}
            />
            <button className="btn btn-success" onClick={handleSimulateResolution} disabled={actionLoading}>
              Execute Simulated Remediation
            </button>
          </div>
        </div>
      )}

      {/* Related Log Evidence Panel */}
      <div className="panel">
        <div className="panel-header">
          <h3 className="panel-title">Related Log Evidence</h3>
        </div>
        <div className="table-container">
          <table className="data-table">
            <thead>
              <tr>
                <th>Timestamp</th>
                <th>Level</th>
                <th>Service</th>
                <th>Message</th>
                <th>Anomaly Score</th>
              </tr>
            </thead>
            <tbody>
              {!incident.related_logs || incident.related_logs.length === 0 ? (
                <tr>
                  <td colSpan="5" style={{ textAlign: 'center', color: 'var(--text-muted)' }}>No related logs found</td>
                </tr>
              ) : (
                incident.related_logs.map((log) => (
                  <tr key={log.id}>
                    <td style={{ fontSize: '12px', whiteSpace: 'nowrap' }}>{log.timestamp}</td>
                    <td>
                      <span className={`badge ${log.level === 'CRITICAL' ? 'badge-critical' : log.level === 'ERROR' ? 'badge-high' : log.level === 'WARN' ? 'badge-medium' : 'badge-low'}`}>
                        {log.level}
                      </span>
                    </td>
                    <td>{log.service}</td>
                    <td style={{ fontFamily: 'monospace', fontSize: '13px' }}>{log.message}</td>
                    <td>
                      <span className="badge badge-critical">
                        {log.anomaly_score}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Resolution History Panel */}
      <div className="panel">
        <div className="panel-header">
          <h3 className="panel-title">Resolution History</h3>
        </div>
        <div className="table-container">
          <table className="data-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Action Taken</th>
                <th>Result</th>
                <th>Timestamp</th>
              </tr>
            </thead>
            <tbody>
              {!incident.resolutions || incident.resolutions.length === 0 ? (
                <tr>
                  <td colSpan="4" style={{ textAlign: 'center', color: 'var(--text-muted)' }}>No resolution actions recorded yet</td>
                </tr>
              ) : (
                incident.resolutions.map((res) => (
                  <tr key={res.id}>
                    <td>#{res.id}</td>
                    <td style={{ fontWeight: 600 }}>{res.action}</td>
                    <td style={{ color: '#166534' }}>{res.result}</td>
                    <td style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
                      {res.created_at ? new Date(res.created_at).toLocaleString() : 'N/A'}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
